// Saturating Up/Down Counter Module
// Counts up or down by a programmable step size (1 to 8)
// Saturates at 0 when counting down and at count_max when counting up

// generated by AI assistant WSGPT
// based on user input and specifications
// - Parameterizable bit width via WIDTH parameter
// - posedge clk
// - Asynchronous active-low reset (rst_n)
// - Up / Down counting via up_down_n
// - Configurable step size (1 … 8) via step_size[2:0]
// - Programmable maximum value (count_max)
// - Saturating behavior at count_max (and at 0 when counting down)
// - Enable-controlled
// - Pure SystemVerilog style

/* verilator lint_off WIDTHEXPAND */

`timescale 1ns/1ps

module sat_counter #(
    parameter int WIDTH = 8
)(
    input  logic                   clk,
    input  logic                   rst_n,              // async, active-low reset
    input  logic                   clear,              // sync, active-high clear
    input  logic                   enable,
    input  logic                   up_down_n,          // 1 = up, 0 = down
    input  logic [2:0]             step_size,          // 0->1, ..., 7->8
    input  logic [WIDTH-1:0]       count_max,
    output logic [WIDTH-1:0]       count,
    output logic                   count_max_reached,
    output logic                   count_zero_reached
);

    // ------------------------------------------------------------
    // Step size mapping: 0 => 1, 7 => 8
    // ------------------------------------------------------------
    logic [WIDTH-1:0] step;
    assign step = step_size + 1'b1;

    // ------------------------------------------------------------
    // Counter logic
    // ------------------------------------------------------------
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            count <= '0;
        end
        else if (clear) begin
            count <= '0;
        end
        else if (enable) begin
            if (up_down_n) begin
                // -------- Count UP (saturating) --------
                if (count >= count_max)
                    count <= count_max;
                else if (count + step >= count_max)
                    count <= count_max;
                else
                    count <= count + step;
            end
            else begin
                // -------- Count DOWN (saturating) --------
                if (count <= step)
                    count <= '0;
                else
                    count <= count - step;
            end
        end
    end

    // ------------------------------------------------------------
    // Terminal indicators (combinational)
    // ------------------------------------------------------------
    always_comb begin
        count_max_reached  = (count == count_max);
        count_zero_reached = (count == '0);
    end

endmodule
